#!/bin/sh
#
# openmediavault-sunburstfs
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

set -e

case "$1" in
    purge)
        rm -rf /var/cache/openmediavault/sunburstfs
        rm -f /run/lock/sunburstfs-*.lock
    ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
